### PR TITLE
Added drag command

### PR DESCRIPTION
**Pull request by Hamy-os**
apparently this is needed as people cant drag and drop

### CODE REVIEW

**Review by LedAndris — CHANGES_REQUESTED** [review]
fix casing for txadmin please

**Review by LedAndris — CHANGES_REQUESTED** [review]
also fix typos

**Review by LedAndris — CHANGES_REQUESTED** [review]
also please clarify the last sentence bec its unclear

**Comment by Hamy-os** [comment]
useless command

**Pull request closed without merging**
