### PR TITLE
New doc links and another Chungus command

### PR DESCRIPTION
**Pull request by PLOKMJNB**

### CODE REVIEW

**Review by HypeLevels — CHANGES_REQUESTED** [review]
Markdown doesn't work in commands that trigger a normal message, this would need to be a rich embed for it to work.

**Review by HypeLevels — COMMENTED** [review]
Can't be accepted yet, docs.txadm.in is not pointing anywhere.

**Review by tabarra — CHANGES_REQUESTED** [review]
Please remove the steam thing, we want to solve txAdmin issues not general fivem issues... or we would need more 50 commands just for the basics.

**Comment by PLOKMJNB** [comment]
> Can't be accepted yet, docs.txadm.in is not pointing anywhere.

**Comment by tabarra** [comment]
outdated

**Pull request closed without merging**
